# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etiqueta', '0001_initial'),
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('tiempoVencimiento', models.DurationField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('etiqueta', models.ManyToManyField(blank=True, to='etiqueta.Etiqueta')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
    ]
