# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 20, 20, 13, 59, 558904)),
        ),
    ]
