# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_auto_20161120_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
