# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0004_auto_20161120_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tiempoVencimiento',
            field=models.DurationField(default='15 00:00:00'),
        ),
    ]
