# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0005_auto_20161121_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
