# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncio', '0006_auto_20161121_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='alumno',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
