# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='etiqquetas',
            new_name='etiquetas',
        ),
    ]
