# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20161116_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='verificador',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
